rabbit1:
  image: "rabbitmq:3-management"
  hostname: "rabbit1"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq1"
  net: host
MongoDB:
  image: sameersbn/mongodb:latest
  ports:
    - "27017:27017"
  restart: always
  net: host